from .registration_view import RegistrationView
from .forget_password_view import ForgetPasswordView
from .user_view import UserDetailView
from .changepassword_view import ChangePasswordView
from .emailexist_view import EmailExistAPIView
from .reset_password_view import ResetPasswordAPIView
from .accountstatus_view import AccountStatusAPIView
from .accountactivation_view import AccountActivationAPIView
